spring:
  application:
    name: issue-tracker
  datasource:
    url: jdbc:mysql://localhost:3306/tracker_db
    username: team09
    password: masters2024team09
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always